version: '3.1'

services:
  device_info_db:
    image: postgres:13.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
  device_info_db_adminer:
    image: adminer
    ports:
      - 8082:8080